BookStore/BookStore/Areas/Admin/Controllers/HomeAdminController.cs
using BookStore.Areas.Admin.Models;
using BookStore.Controllers;
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    public class HomeAdminController : BaseADMINController
    {
        // GET: Admin/HomeAdmin
         BookstoreEntities db = new BookstoreEntities();
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Book b = db.Books.SingleOrDefault(m => m.ID == id);
            BookTempModel t = new BookTempModel()
            {
                ID = b.ID,
                Name = b.Name,
                AuthorID = b.AuthorID,
                BookTypeID = b.BookTypeID,
                Decription = b.Decription,
                ImagePath = b.ImagePath,
                Note = b.Note,
                NumberOfInventory = b.NumberOfInventory,
                Price = b.Price.ToString(),
                PublisherID = b.PublisherID,
                UpdateDate = b.UpdateDate
            };
            BookModel x = new BookModel()
            {
                authors = db.Authors.ToList(),
                categories = db.Categories.ToList(),
                publishers = db.Publishers.ToList(),
                book = t
            };
            return View(x);
        }

        [HttpPost]
        public JsonResult Edit(BookModel data)
        {
            try
            {
                Book t = db.Books.SingleOrDefault(m => m.ID == data.book.ID);
                t.Name = data.book.Name;
                t.Price = double.Parse(data.book.Price.ToString(), CultureInfo.CreateSpecificCulture("en-US"));
                t.Decription = data.book.Decription;
                t.NumberOfInventory = data.book.NumberOfInventory;
                t.Note = data.book.Note;
                t.ImagePath = data.book.ImagePath;
                t.BookTypeID = data.book.BookTypeID;
                t.AuthorID = data.book.AuthorID;
                t.PublisherID = data.book.PublisherID;
                db.SaveChanges();
                return Json(new { status = true });
            }
            catch
            {
                return Json(new { status = false });

            }

        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            Book x = db.Books.SingleOrDefault(m => m.ID == id);
            db.Books.Remove(x);
            db.SaveChanges();
            return RedirectToAction("ListBook");
        }

        [HttpGet]
        public ActionResult ListBook()
        {
            IEnumerable<Book> lst = db.Books.ToList();
            return View(lst);
        }

        [HttpGet]
        [ActionName("CreateNewBook")]
        public ActionResult CreateNewBook()
        {
            return View();
        }
        [HttpPost]
        [ActionName("CreateNewBook")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNewBook(BookModel x)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    Book b = new Book()
                    {
                        Name = x.book.Name,
                        Price = double.Parse(x.book.Price.ToString(), CultureInfo.CreateSpecificCulture("en-US")),
                        Decription = x.book.Decription,
                        NumberOfInventory = x.book.NumberOfInventory,
                        UpdateDate = DateTime.Now,
                        Note = x.book.Note,
                        ImagePath = x.book.ImagePath,
                        BookTypeID = x.book.BookTypeID,
                        AuthorID = x.book.AuthorID,
                        PublisherID = x.book.PublisherID

                    };
                    db.Books.Add(b);
                    db.SaveChanges();
                    return RedirectToAction("CreateNewBook");
                }
                else
                    return View(x);
            }
            catch
            {
                return View(x);
            }



        }

        public ActionResult Success()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AddAuthor(string AuthorName, string job)
        {
            try
            {
                Author a = new Author()
                {
                    Name = AuthorName,
                    Job = job
                };
                db.Authors.Add(a);
                db.SaveChanges();
                return Json(new { status = true });

            }
            catch
            {
                return Json(new { status = false });

            }

        }

        [HttpPost]
        public JsonResult AddCategory(string category)
        {
            try
            {
                Category x = new Category() { Name = category };
                db.Categories.Add(x);
                db.SaveChanges();
                return Json(new { status = true });
            }
            catch
            {
                return Json(new { status = false });
            }
        }
    }
}

BookStore/BookStore/Areas/Admin/Views/HomeAdmin/CreateNewBook.cshtml
@using BookStore.Areas.Admin.Models;
@using BookStore.Models;
@model BookModel
@{
    BookstoreEntities db = new BookstoreEntities();
}

@{
    ViewBag.Title = "CreateNewBook";

    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



@section jsFooter{
    <script src="~/Areas/Admin/js/Scripts/mainJS.js">
    </script>
}
<h2>Thêm mới sách</h2>

@using (Html.BeginForm("CreateNewBook", "HomeAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("BookType", "Loại sách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => Model.book.BookTypeID, db.Categories.ToList().Select(m => new SelectListItem
           {
               Text = m.Name,
               Value = m.ID.ToString()

           }

           ), "--Loại sách--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.book.BookTypeID, "", new { @class = "text-danger" })

                <button class="btn btn-light" id="addCategory">Thêm thể loại</button>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Author", "Tác giả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => Model.book.AuthorID, db.Authors.ToList().Select(m => new SelectListItem
           {
               Text = m.Name,
               Value = m.ID.ToString()
           }

           ), "--Tác giả--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.book.AuthorID, "", new { @class = "text-danger" })

                <button class="btn btn-light" id="addAuthor">Thêm tác giả</button>
            </div>
        </div>

        <div class="form-group">

            @Html.Label("Publisher", "Nhà xuất bản", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => Model.book.PublisherID, db.Publishers.ToList().Select(m => new SelectListItem
           {
               Text = m.Name,
               Value = m.ID.ToString()
           }

           ), "--Nhà xuất bản--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.book.PublisherID, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.Label("Name", "Tên Sách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Name, new { htmlAttributes = new { @class = "form-control", @style = "width:50%;" } })
                @Html.ValidationMessageFor(model => model.book.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Price", "Giá", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Price, new { htmlAttributes = new { @class = "money form-control", @style = "width:50%;" } })
                @Html.ValidationMessageFor(model => model.book.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Decription", "Mô tả", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.TextAreaFor(model => model.book.Decription, new { @class = "form-control", @style = "width:50%;", @cols = "50", rows = "10" })
                @Html.ValidationMessageFor(model => model.book.Decription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("NumberOfInventory", "Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.book.NumberOfInventory, new { htmlAttributes = new { @class = "form-control", @style = "width:50%;" } })
                @Html.ValidationMessageFor(model => model.book.NumberOfInventory, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("Note", "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.book.Note, new { @class = "form-control", @style = "width:50%;", @cols = "50", rows = "5" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("ImagePath", "Ảnh", htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.TextBoxFor(model => model.book.ImagePath, new { htmlAttributes = new { @class = "form-control", @style = "width:50%;" } })
                <button id="btnChooseImage">Chọn Ảnh</button>
                @Html.ValidationMessageFor(model => model.book.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script type="text/javascript" src="~/Scripts/FomatCurrency.js"></script>
<script type="text/javascript">
    $('.money').simpleMoneyFormat();
</script>

BookStore/BookStore/Areas/Admin/Views/HomeAdmin/Edit.cshtml
@model BookStore.Areas.Admin.Models.BookModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section jsFooter{
    <script src="~/Areas/Admin/js/Scripts/mainJS.js"></script>
}
<h2>Sửa sách</h2>

<form class="frmEdit">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.book.ID)

        <div class="form-group">
            @Html.Label("Name", "Tên Sách", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Price", "Giá", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Price, new { htmlAttributes = new { @class = "money form-control" } } )
                @Html.ValidationMessageFor(model => model.book.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Decription", "Mô tả", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.book.Decription, new { @class = "form-control", @cols = "30", rows = "10" })
                @Html.ValidationMessageFor(model => model.book.Decription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.NumberOfInventory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.NumberOfInventory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.NumberOfInventory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.UpdateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.UpdateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.UpdateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.book.Note, new { @class = "form-control", @cols = "30", rows = "10" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.BookTypeID, "BookTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.book.BookTypeID, Model.categories.Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.ID.ToString()
            }

            ), "--Thể loại--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.book.BookTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tác Giả", "AuthorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.book.AuthorID, Model.authors.Select(m => new SelectListItem
            {
                Text = m.Name,
                Value = m.ID.ToString()
            }

            ), "--Tác giả--", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.PublisherID, "PublisherID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.book.PublisherID, Model.publishers.Select(m => new SelectListItem
             {
                 Text = m.Name,
                 Value = m.ID.ToString()
             }

             ), "--Nhà xuất bản--", new { @class = "form-control" }) @Html.ValidationMessageFor(model => model.book.PublisherID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu lại" class="btn btn-default btnSaveBook" />
            <button type="button" class="btn btn-danger"><a href="/Admin/HomeAdmin/ListBook">Trở về</a></button>
        </div>
    </div>
</div>
</form>

<script type="text/javascript" src="~/Scripts/FomatCurrency.js"></script>
<script type="text/javascript">
    $('.money').simpleMoneyFormat();
</script>

BookStore/BookStore/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

    <div class="jumbotron" style="margin-bottom:50%">
        <h1>Book Store</h1>
        <p>Chào mừng bạn đến với trang quản trị</p>
    </div>

BookStore/BookStore/Areas/Admin/Views/HomeAdmin/ListBook.cshtml
@{
    ViewBag.Title = "ListBook";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<BookStore.Models.Book>

@using BookStore;
@using System;
<h2>Danh Sách sách</h2>


<table class="table">
    <tr>
        <th>
            Tên Sách
        </th>
        <th>
            Giá
        </th>
        <th>
            Mô tả
        </th>
        <th>
            Số lượng có
        </th>
        <th>
            Ngày cập nhật
        </th>
        <th>
            Ghi chú
        </th>
        <th>
            Ảnh bìa
        </th>
        <th>
            Tác giả
        </th>
        <th>
            Thể loại
        </th>
        <th>
            Nhà xuất bản
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>

            @{
                if (item.Decription.Length > 100)
                {
                    <td>
                        @item.Decription.Substring(0, 100) ...
                    </td>
                }
                else
                {
                    <td>  @Html.DisplayFor(modelItem => item.Decription) </td>
                }
            }


            <td>
                @Html.DisplayFor(modelItem => item.NumberOfInventory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdateDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                <img src="@Url.Content(item.ImagePath)" style="width:30px; height:30px;" alt="images" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher.Name)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.ID }, new { onclick = "return confirm('Bạn có muốn xóa " + item.Name + "?')" })
            </td>
        </tr>
    }

</table>

BookStore/BookStore/Areas/Admin/Views/HomeAdmin/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
    <div style="text-align:center; margin-bottom:100px;">
        <h2>Thêm thành công</h2>
        @using (Html.BeginForm("CreateNewBook", "HomeAdmin", FormMethod.Get))
        {
            <button class="btn btn-info" type="submit">Tiếp tục</button>
        }
    </div>